### ISSUE TITLE
account got banned

### ISSUE THREAD

**Issue by qiangweihewu** [sshrshnv/tgstorage#20]
My account got banned during the first time I logged into it on the website tgstorage.com. There could be something not following or satisfying the official requirements of using their APIs.

**Comment by sh-a-v** [comment]
Few accounts have already been blocked and soon unblocked, but the reason could not be found out. Telegram support is not responding to me.

You need to send an email to `recover@telegram.org`, your account will be unblocked during the day.
Example:
```
Banned phone number: 0000

I'm trying to use my mobile phone number:
0000
But Telegram says it's banned. Please help.
```
`0000` - your phone number.

In response, they send an email:
```
Hello,

The issue with your phone number should be solved now, please check.

We apologize for all the inconvenience caused.
Do not hesitate to contact us again if you encounter any similar problem.

Please contact our support service (Settings - Ask a Question), should
you have any questions about Telegram.

Regards,
Telegram Recovery Team
```

**Comment by DandyDrop** [comment]
> Few accounts have already been blocked and soon unblocked, but the reason could not be found out. Telegram support is not responding to me.
> 
> You need to send an email to `recover@telegram.org`, your account will be unblocked during the day. Example:
> 
> ```
> Banned phone number: 0000
> 
> I'm trying to use my mobile phone number:
> 0000
> But Telegram says it's banned. Please help.
> ```
> 
> `0000` - your phone number.
> 
> In response, they send an email:
> 
> ```
> Hello,
> 
> The issue with your phone number should be solved now, please check.
> 
> We apologize for all the inconvenience caused.
> Do not hesitate to contact us again if you encounter any similar problem.
> 
> Please contact our support service (Settings - Ask a Question), should
> you have any questions about Telegram.
> 
> Regards,
> Telegram Recovery Team
> ```

What if I have bought the acc, will they recover my logins or I won`t be able to take my acc back if number isn`t mine?
