### ISSUE TITLE
Hide folders created

### ISSUE THREAD

**Issue by zakiloki0** [sshrshnv/tgstorage#21]
The project is very nice and useful, but I found something a bit annoying. When creating the folders in TGStorage the concept works super well, but then I go to my mobile and see a lot of channels created and "dirty" my chat list, wouldn't it be better if they could be hidden? Because it doesn't make much sense for him to behave like that.

**Comment by sshrshnv** [comment]
The created channels (TgStorage folders) are archived by default, they should not be displayed in the official Telegram app.

**Comment by zakiloki0** [comment]
Even if it were (which is not my case as I commented) is there no way to make it invisible? Understanding that the Telegram API works like this then, too bad :(

**Comment by sshrshnv** [comment]
You can manually archive channels in the official application and they will not be displayed in the general list. If they are displayed in a certain folder, then you just need to delete them from it.
