### ISSUE TITLE
Приложение для Виндовс

### ISSUE THREAD

**Issue by constantin-online** [sshrshnv/tgstorage#24]
Привет. Вы будите делать его приложением для Виндовс? Мне было бы удобнее так.

**Comment by sshrshnv** [comment]
Hello! You can install the app on Windows 11 from Chrome or Microsoft Edge browser.

![image_2023-09-18_00-09-02](https://github.com/sshrshnv/tgstorage/assets/7159528/839302d9-68e9-4f00-99a2-49b161a23d36)

**Comment by constantin-online** [comment]
It doesn't show up in my browser. I have to go to tgstorage.com every time to download.
